删除d_worker中一些同步方法 fixbug: Downloader重复下载 添加Grafana指标检控

diff --git a/.github/workflows/alist-sync.yaml b/.github/workflows/alist-sync.yaml
--- a/.github/workflows/alist-sync.yaml
+++ b/.github/workflows/alist-sync.yaml
@@ -50,6 +50,22 @@ jobs:
             ./.alist-sync-cache/*.shelve
             ./alist/data
 
+      - name: Install Grafana Agent
+        if: secrets.GRAFANA_AGENT_CONFIG
+        run: |          
+          cat > /etc/grafana-agent.yaml << EOF
+          ${{ secrets.GRAFANA_AGENT_CONFIG }}
+          EOF
+          
+          sed -i "s/instance: <your-instance-name>/instance: ${_ALIST_SYNC_NAME}/g" /etc/grafana-agent.yaml
+          sed -i "s#<your-log-path>#$(pwd)/logs/*.log#g" /etc/grafana-agent.yaml
+          
+          curl -fL# https://github.com/grafana/agent/releases/download/v0.39.1/grafana-agent-0.39.1-1.amd64.deb -o grafana-agent-0.39.1-1.amd64.deb
+          echo -n "19ba2f69ec14fae4812128475beea6e034e7e9c1183cd0c1f6814d04d0ba788b  grafana-agent-0.39.1-1.amd64.deb" | sha256sum -c - 2>&1 | grep "OK" || fatal 'Failed sha256sum check'
+          sudo dpkg -i "/tmp/grafana-agent-0.39.1-1.amd64.deb"
+          sudo systemctl enable grafana-agent.service
+          sudo systemctl start grafana-agent.service
+
       - name: Install and Init Alist Server
         run: |
           sudo ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
@@ -113,7 +129,7 @@ jobs:
           fi
 
       - name: Debugger
-        if: ${{ github.event.inputs.debug == 'true' && failure() }}
+        if: ${{ github.event.inputs.debug == 'true' && always() }}
         uses: csexton/debugger-action@master
 
       - name: Upload Logs
